# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------
# Name: extract_main_ridges_algorithm.py
#
# Purpose: QGIS Processing Algorithm to extract main ridge lines based on flow accumulation
#
# -----------------------------------------------------------------------------
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessingAlgorithm, QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterVectorDestination,
                       QgsProcessingParameterNumber, QgsProcessingParameterBoolean,
                       QgsProcessing, QgsProcessingParameterFeatureSource, QgsProcessingException)
import os
import gc
import uuid
from .utils import get_crs_from_layer, ensure_whiteboxtools_configured, save_gdf_to_file, save_gdf_to_file_ogr, load_gdf_from_file, load_gdf_from_file_ogr, load_gdf_from_qgis_source, get_vector_ext, get_crs_from_project, clear_pyproj_cache
from shapely.ops import transform as _shapely_transform

pluginPath = os.path.dirname(__file__)

class ExtractMainRidgesAlgorithm(QgsProcessingAlgorithm):
    """
    QGIS Processing Algorithm for extracting main ridge lines using ridge lines generated by "Extract Ridges".

    Tributary selection is based on the pre-computed TRIB_RANK attribute (added automatically by the
    Extract Ridges tool). No flow-accumulation raster input is needed.

    The algorithm:
    - Clips ridge lines to the specified perimeter (or uses full extent if none provided)
    - Selects the top N ridges by TRIB_RANK (rank 1 = highest flow accumulation on inverted DTM)
    - Merges line segments belonging to each selected ridge

    This is useful for identifying the most significant watershed divides (ridges) in a watershed
    or study area, focusing analysis on the primary ridges resp. drainage divides.
    """

    INPUT_RIDGE_LINES = 'INPUT_RIDGE_LINES'
    INPUT_PERIMETER = 'INPUT_PERIMETER'
    OUTPUT_MAIN_RIDGES = 'OUTPUT_MAIN_RIDGES'
    NR_MAIN = 'NR_MAIN'
    CLIP_TO_PERIMETER = 'CLIP_TO_PERIMETER'
    SMOOTH_OUTPUT = 'SMOOTH_OUTPUT'
    SMOOTH_FILTER_SIZE = 'SMOOTH_FILTER_SIZE'

    def __init__(self, core=None):
        super().__init__()
        self.core = core  # Should be set to a TopoDrainCore instance by the plugin

    def set_core(self, core):
        self.core = core
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        instance = ExtractMainRidgesAlgorithm(core=self.core)
        if hasattr(self, 'plugin'):
            instance.plugin = self.plugin
        return instance

    def name(self):
        return 'extract_main_ridges'

    def displayName(self):
        return self.tr('Extract Main Ridges')

    def group(self):
        return self.tr('Basic Watershed Analysis')

    def groupId(self):
        return 'basic_watershed_analysis'

    def shortHelpString(self):
        return self.tr(
            """Extract main ridge lines from a complete ridge network using TRIB_FACC / TRIB_RANK computed by the Extract Ridges tool. No flow-accumulation raster is required.

Ridges are selected globally across all disconnected sub-networks by maximum flow accumulation on the inverted DTM (TRIB_FACC). This means the nr_main most significant ridges over the entire study area are selected.

The algorithm:
- Clips ridge lines to the specified perimeter (or uses full extent if none provided)
- Selects the top N ridges by TRIB_FACC (highest flow accumulation first, global across all networks)
- Merges line segments belonging to each selected ridge

Input Requirements:
- Ridge Lines: Must have 'LINK_ID', 'TRIB_ID', 'DS_LINK_ID', and 'TRIB_RANK' attributes (output of Extract Ridges algorithm). 'TRIB_FACC' is used for sorting when present (current Create Ridges algorithm).
- Perimeter (optional): Polygon defining the study area boundary. If not provided, uses the extent of ridge lines.

Output attributes: LINK_ID, TRIB_ID, RANK (1=highest flow accumulation in selection), TRIB_RANK (global rank from input), POLYGON_ID, DS_LINK_ID"""
        )
    
    def icon(self):
        return QIcon(os.path.join(pluginPath, 'icons', 'topo_drain.svg'))

    def initAlgorithm(self, config=None):        
        # Input parameters
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_RIDGE_LINES,
                self.tr('Input Ridge Lines (must have LINK_ID, TRIB_ID, DS_LINK_ID, TRIB_RANK, TRIB_FACC attributes)'),
                types=[QgsProcessing.TypeVectorLine]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT_PERIMETER,
                self.tr('Input Perimeter Polygon (area of interest)'),
                types=[QgsProcessing.TypeVectorPolygon],
                optional=True
            )
        )
        
        # Algorithm parameters
        self.addParameter(
            QgsProcessingParameterNumber(
                self.NR_MAIN,
                self.tr('Number of main ridges to extract'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=2,
                minValue=1
            )
        )
        
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.CLIP_TO_PERIMETER,
                self.tr('Clip output to perimeter (if perimeter provided)'),
                defaultValue=True
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.SMOOTH_OUTPUT,
                self.tr('Smooth output lines (uses WBT SmoothVectors)'),
                defaultValue=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.SMOOTH_FILTER_SIZE,
                self.tr('Smooth filter size (number of vertices to average)'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=6,
                minValue=3,
                optional=True
            )
        )
        main_ridges_param = QgsProcessingParameterVectorDestination(
            self.OUTPUT_MAIN_RIDGES,
            self.tr('Output Main Ridge Lines'),
            type=QgsProcessing.TypeVectorLine,
            defaultValue=None
        )
        self.addParameter(main_ridges_param)

    def processAlgorithm(self, parameters, context, feedback):
        # CRITICAL: Clear PyProj cache at start to prevent Windows crashes on repeated runs
        #clear_pyproj_cache(feedback) # seems not to resolve the issue
        
        # Ensure WhiteboxTools is configured before running
        if not ensure_whiteboxtools_configured(self, feedback):
            return {}
        
        # Validate and read input parameters
        ridge_lines_layer = self.parameterAsVectorLayer(parameters, self.INPUT_RIDGE_LINES, context)
        perimeter_layer = self.parameterAsSource(parameters, self.INPUT_PERIMETER, context)

        # Get file paths and validate formats
        ridge_lines_path = ridge_lines_layer.source()
        ridge_ext = get_vector_ext(ridge_lines_path, feedback)
        
        # Create supported formats lists
        supported_vector_formats = list(self.core.ogr_driver_mapping.keys()) if hasattr(self.core, 'ogr_driver_mapping') else []
        
        # Validate vector format compatibility with OGR driver mapping (warning only)
        if hasattr(self.core, 'ogr_driver_mapping') and ridge_ext not in self.core.ogr_driver_mapping:
            feedback.pushWarning(f"Ridge lines format '{ridge_ext}' is not in OGR driver mapping. Supported formats: {supported_vector_formats}. GeoPandas will attempt to load it automatically.")
        
        # Use parameterAsOutputLayer to preserve checkbox state information
        main_ridges_output_layer = self.parameterAsOutputLayer(parameters, self.OUTPUT_MAIN_RIDGES, context)
        
        # Get algorithm parameters
        nr_main = self.parameterAsInt(parameters, self.NR_MAIN, context)
        clip_to_perimeter = self.parameterAsBool(parameters, self.CLIP_TO_PERIMETER, context)
        smooth_output = self.parameterAsBool(parameters, self.SMOOTH_OUTPUT, context)
        smooth_filter_size = self.parameterAsInt(parameters, self.SMOOTH_FILTER_SIZE, context)

        # Extract actual file path from layer object for processing
        main_ridges_file_path = main_ridges_output_layer
        
        # Validate output vector format compatibility with OGR driver mapping
        output_ext = get_vector_ext(main_ridges_file_path, feedback, check_existence=False)
        if hasattr(self.core, 'ogr_driver_mapping') and output_ext not in self.core.ogr_driver_mapping:
            feedback.pushWarning(f"Output file format '{output_ext}' is not in OGR driver mapping. Supported formats: {supported_vector_formats}. GeoPandas will attempt to save it automatically.")

        # Adjust core crs with project crs if needed
        feedback.pushInfo(f"Core CRS: {self.core.crs}")
        project_crs = get_crs_from_project()
        feedback.pushInfo(f"Project CRS: {project_crs}")
        if self.core.crs is None and project_crs is None:
            feedback.pushWarning("Both core CRS and project CRS are None - CRS may not be properly set")
        elif project_crs != self.core.crs:
            if project_crs is None:
                feedback.pushWarning("Project CRS is None - keeping core CRS") 
            else:
                feedback.pushInfo(f"Setting core CRS from project CRS: {project_crs}")
                self.core.set_crs(project_crs)

        # Check input crs against core crs
        feedback.pushInfo("Reading CRS from ridge lines...")
        ridge_crs = get_crs_from_layer(ridge_lines_layer)
        feedback.pushInfo(f"Ridge lines CRS: {ridge_crs}")
        # Adjust core crs with input crs but only if it is None
        if self.core.crs is None:
            feedback.pushInfo(f"Setting core CRS from ridge lines CRS: {ridge_crs}")
            self.core.set_crs(ridge_crs)
        elif ridge_crs != self.core.crs:
            # Add warning if input crs not equal to core crs
            feedback.pushWarning(f"Ridge lines CRS {ridge_crs} differs from core (project) CRS {self.core.crs}!")

        # Load input data as GeoDataFrame - use OGR on Windows to avoid PyProj
        feedback.pushInfo("Loading ridge lines...")
        try:
            if self.core.disable_crs_operations:
                feedback.pushInfo("Loading ridge lines WITHOUT CRS to avoid PyProj issues...")
                ridge_lines_gdf = load_gdf_from_file_ogr(ridge_lines_path, feedback)
            else:
                ridge_lines_gdf = load_gdf_from_file(ridge_lines_path, feedback)
            feedback.pushInfo(f"Successfully loaded {len(ridge_lines_gdf)} ridge line features")
        except Exception as e:
            feedback.pushInfo(f"Failed to load ridge lines: {e}")
            raise QgsProcessingException(f"Failed to load ridge lines: {e}")

        if ridge_lines_gdf.empty:
            raise QgsProcessingException("No features found in ridge lines input")

        # Load perimeter if provided, otherwise will be None (and core function will handle it)
        perimeter_gdf = None
        if perimeter_layer:
            feedback.pushInfo("Loading perimeter...")
            try:
                # Load perimeter features with automatic data cleaning
                perimeter_gdf = load_gdf_from_qgis_source(perimeter_layer, feedback)
                if not perimeter_gdf.empty:
                    feedback.pushInfo(f"Successfully loaded {len(perimeter_gdf)} perimeter features")
            except Exception as e:
                feedback.pushInfo(f"Failed to load perimeter: {e}")
                raise QgsProcessingException(f"Failed to load perimeter: {e}")
        else:
            feedback.pushInfo("No perimeter provided, will use ridge lines extent")

        if perimeter_gdf is not None and perimeter_gdf.empty:
            feedback.reportError("No features found in perimeter input")

        # Check for required attributes (case-insensitive)
        feedback.pushInfo(f"Checking ridge lines attributes: {list(ridge_lines_gdf.columns)}")
        required_attrs = ['LINK_ID', 'TRIB_ID', 'DS_LINK_ID', 'TRIB_RANK']
        # Convert column names to uppercase for case-insensitive comparison
        available_attrs_upper = [col.upper() for col in ridge_lines_gdf.columns]
        feedback.pushInfo(f"Ridge lines attributes (uppercase): {available_attrs_upper}")
        missing_attrs = [attr for attr in required_attrs if attr not in available_attrs_upper]
        if missing_attrs:
            raise QgsProcessingException(f"Ridge lines missing required attributes: {missing_attrs}. Please use output from the current Create Ridges algorithm. Available attributes: {list(ridge_lines_gdf.columns)}")

        # Call the core function
        feedback.pushInfo("Running extract main ridges...")
        main_ridges_gdf = self.core.extract_main_ridges(
            ridge_lines=ridge_lines_gdf,
            perimeter=perimeter_gdf,
            nr_main=nr_main,
            clip_to_perimeter=clip_to_perimeter,
            feedback=feedback
        )

        if main_ridges_gdf.empty:
            raise QgsProcessingException("No main ridges were detected")

        feedback.pushInfo(f"Created {len(main_ridges_gdf)} main ridges")

        if smooth_output:
            feedback.pushInfo(f"[ExtractMainRidges] Smoothing output (filter_size={smooth_filter_size})...")
            smoothed_gdf = None
            # Strip any Z dimension: whitebox_workflows' Vector model derives from the classic
            # Shapefile geometry model, and a 3D geometry type declaration is a likely cause of
            # its "must be of POLYLINE or POLYGON base shape type" rejection.
            smooth_source_gdf = main_ridges_gdf.copy()
            smooth_source_gdf['geometry'] = smooth_source_gdf.geometry.apply(
                lambda g: _shapely_transform(lambda x, y, z=None: (x, y), g)
            )
            # GPKG first (matches all other temp I/O); if whitebox_workflows rejects our
            # hand-written GPKG geometry type, retry once with Shapefile before giving up.
            for smooth_ext in (".gpkg", ".shp"):
                smooth_input_path = os.path.join(self.core.temp_directory, f"smooth_input_{uuid.uuid4().hex[:8]}{smooth_ext}")
                smooth_output_path = os.path.join(self.core.temp_directory, f"smooth_output_{uuid.uuid4().hex[:8]}{smooth_ext}")
                save_gdf_to_file_ogr(smooth_source_gdf, smooth_input_path, self.core, feedback)
                try:
                    ret = self.core.wbt_executor(
                        'smooth_vectors',
                        feedback=feedback,
                        report_progress=False,
                        input=smooth_input_path,
                        output=smooth_output_path,
                        filter_size=smooth_filter_size,
                    )
                    if ret != 0 or not os.path.exists(smooth_output_path):
                        raise RuntimeError(f"smooth_vectors returned {ret}")
                    candidate_gdf = load_gdf_from_file_ogr(smooth_output_path, feedback)
                    if candidate_gdf.empty:
                        raise RuntimeError("smoothed result is empty")
                    smoothed_gdf = candidate_gdf
                    break
                except Exception as e:
                    if smooth_ext == ".gpkg":
                        feedback.pushWarning(f"[ExtractMainRidges] Smoothing via GPKG failed ({e}), retrying via Shapefile...")
                    else:
                        feedback.pushWarning(f"[ExtractMainRidges] Smoothing failed: {e}, using unsmoothed result")
            if smoothed_gdf is not None:
                main_ridges_gdf = smoothed_gdf
                feedback.pushInfo("[ExtractMainRidges] Smoothing applied successfully")

        # Save result - use OGR on Windows to avoid PyProj crashes
        if self.core.disable_crs_operations:
            feedback.pushInfo("Saving main ridges WITHOUT setting CRS to avoid WINDOWS PyProj issues...")   
            save_gdf_to_file_ogr(main_ridges_gdf, main_ridges_file_path, self.core, feedback)
        else:
            feedback.pushInfo("Saving main ridges WITH setting CRS pyproj (geopandas)...")
            save_gdf_to_file(main_ridges_gdf, main_ridges_file_path, self.core, feedback)
        
        results = {}
        # Add output parameters to results
        for output in self.outputDefinitions():
            outputName = output.name()
            if outputName in parameters:
                results[outputName] = parameters[outputName]

        return results
