# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TopoDrainPlugin
                                 A QGIS plugin
 A QGIS plugin for planning surface drainage water management. It automates the extraction of main valleys and ridges, and supports various other water retention planning methods, such as Keyline Design (keypoints, keylines), pond siting and various other sponge-scape measures. The algorithms are mainly based on whitebox_workflows. The plugin will be developed further on a regular basis.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-06
        copyright            : (C) 2025 by Timo Wicki
        email                : wickitimo@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Timo Wicki'
__date__ = '2025-08-06'
__copyright__ = '(C) 2025 by Timo Wicki'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect
import importlib
import logging

_log = logging.getLogger(__name__)

from qgis.core import QgsProcessingAlgorithm, QgsApplication, QgsProcessingUtils, QgsCoordinateReferenceSystem, QgsProject, QgsRasterLayer, QgsVectorLayer
from qgis.PyQt.QtWidgets import QMessageBox
from .topo_drain_provider import TopoDrainProvider
from topo_drain.core.topo_drain_core import TopoDrainCore
from .utils import get_crs_from_project

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)

class TopoDrainPlugin(object):

    def __init__(self):
        self.provider = None
        self.core = None  # Will hold the TopoDrainCore instance

    def check_python_dependencies(self):
        """Return True if all required packages are present, else show an install dialog."""
        # import_name -> pip package name
        REQUIRED = {
            "numpy": "numpy",
            "pandas": "pandas",
            "geopandas": "geopandas",
            "shapely": "shapely",
            "scipy": "scipy",
            "whitebox_workflows": "whitebox-workflows",
        }
        missing = [
            pip_name
            for import_name, pip_name in REQUIRED.items()
            if importlib.util.find_spec(import_name) is None
        ]
        if not missing:
            return True
        self._show_missing_deps_dialog(missing)
        return False

    def _build_install_command(self, packages: list) -> str:
        """Return an exec() string safe to paste into the QGIS Python Console."""
        if os.name == "nt":
            pip_args = str(["pip", "install"] + packages)
        else:
            pip_args = str(["pip", "install", "--user"] + packages)

        inner = (
            "import runpy,sys\\n"
            "try:\\n"
            "    import pip\\n"
            "except ImportError:\\n"
            "    import ensurepip\\n"
            "    ensurepip.bootstrap(upgrade=True)\\n"
            f"sys.argv={pip_args}\\n"
            "try:\\n"
            "    runpy.run_module('pip',run_name='__main__',alter_sys=True)\\n"
            "except SystemExit:\\n"
            "    pass\\n"
            "import qgis.utils\\n"
            "qgis.utils.unloadPlugin('topo_drain')\\n"
            "qgis.utils.loadPlugin('topo_drain')\\n"
            "qgis.utils.startPlugin('topo_drain')\\n"
            "print('TopoDrain dependencies installed and plugin reloaded.')"
        )
        return f'exec("{inner}")'

    def _show_missing_deps_dialog(self, missing: list) -> None:
        """Show a dialog with step-by-step install instructions for missing packages."""
        command = self._build_install_command(missing)
        try:
            from qgis.PyQt.QtWidgets import (
                QDialog, QVBoxLayout, QHBoxLayout,
                QLabel, QPlainTextEdit, QPushButton, QApplication,
            )
            from qgis.PyQt.QtGui import QFont

            parent = None
            try:
                from qgis.utils import iface as _iface
                if _iface is not None:
                    parent = _iface.mainWindow()
            except Exception as exc:
                _log.debug("Could not get QGIS main window: %s", exc)

            dlg = QDialog(parent)
            dlg.setWindowTitle("⚠️  Action Required — Install TopoDrain Dependencies")
            dlg.setMinimumWidth(660)

            layout = QVBoxLayout(dlg)
            layout.setSpacing(10)

            header = QLabel("<b style='font-size:13px;'>Required Python packages are missing.</b>")
            header.setWordWrap(True)
            header.setStyleSheet("color: #b34700; padding: 4px 0;")
            layout.addWidget(header)

            pkg_list = ", ".join(f"<b>{p}</b>" for p in missing)
            instructions = (
                f"The following packages are required but not installed: {pkg_list}.<br><br>"
                "To install them:<ol>"
                "<li>Open the QGIS Python Console:&nbsp;&nbsp;<b>Plugins &nbsp;&#9656;&nbsp; Python Console</b></li>"
                "<li>Click <b>Copy command to clipboard</b> below, paste it into the console, "
                "and press <b>Enter</b>.</li>"
                "<li>The packages will install and the plugin will reload automatically — "
                "no QGIS restart needed.</li>"
                "</ol>"
            )
            lbl = QLabel(instructions)
            lbl.setWordWrap(True)
            lbl.setOpenExternalLinks(False)
            layout.addWidget(lbl)

            layout.addWidget(QLabel("<b>Command to paste in the Python Console:</b>"))

            cmd_edit = QPlainTextEdit(command)
            cmd_edit.setReadOnly(True)
            font = QFont()
            font.setFamily("Courier New" if os.name == "nt" else "Menlo")
            font.setPointSize(10)
            cmd_edit.setFont(font)
            cmd_edit.setFixedHeight(140)
            layout.addWidget(cmd_edit)

            btn_row = QHBoxLayout()

            copy_btn = QPushButton("📋  Copy command to clipboard")
            copy_btn.setDefault(True)

            def _copy():
                try:
                    QApplication.clipboard().setText(command)
                    copy_btn.setText("✓  Copied!")
                except Exception as exc:
                    _log.debug("Clipboard copy failed: %s", exc)

            copy_btn.clicked.connect(_copy)
            btn_row.addWidget(copy_btn)
            btn_row.addStretch()

            close_btn = QPushButton("Close")
            close_btn.setDefault(False)
            close_btn.setAutoDefault(False)
            close_btn.clicked.connect(dlg.accept)
            btn_row.addWidget(close_btn)

            layout.addLayout(btn_row)

            dlg.exec() if hasattr(dlg, "exec") and callable(dlg.exec) else dlg.exec_()

        except Exception:
            # Last-resort fallback if Qt widgets are unavailable
            QMessageBox.critical(
                None,
                "TopoDrain Plugin — Missing Dependencies",
                "Missing packages: " + ", ".join(missing) +
                "\n\nOpen the QGIS Python Console (Plugins → Python Console) and run:\n\n" +
                command,
            )
    
    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        temp_dir = QgsProcessingUtils.tempFolder()
        working_dir = QgsProcessingUtils.tempFolder()

        print("whitebox_workflows is used directly; no WhiteboxTools executable setup is required")
        
        project_crs = get_crs_from_project()
        # WBW corrupts PROJ's shared global state on all platforms; always use OGR-safe paths.
        disable_crs = True
        print(f"[TopoDrain Plugin] Running on {sys.platform} - CRS operations disabled (WBW/PROJ conflict)")
        
        self.core = TopoDrainCore(whitebox_directory=None, crs=project_crs, temp_directory=temp_dir, working_directory=working_dir, disable_crs_operations=disable_crs)
        
        # Only check dependencies after core is created
        self.check_python_dependencies()
        
        # Pass the core instance to the provider
        self.provider = TopoDrainProvider(core=self.core, plugin=self)
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        
    def ensure_whiteboxtools_configured(self):
        """
        Ensure whitebox_workflows is configured. This method can be called by algorithms
        before they execute to make sure the workflow runtime is available.
        
        Returns:
            bool: True if whitebox_workflows is configured, False otherwise
        """
        if self.core is None:
            return False

        try:
            runtime = self.core.get_wbw_runtime(include_pro=False, tier="open")
            # Always rebuild the session for each algorithm run. Reusing a RuntimeSession
            # across separate Processing runs (even from the same pooled thread) triggers an
            # unrecoverable Rust-side assert/abort inside whitebox_workflows on the Nth run.
            # This re-adds a brief per-run construction cost, but avoids a hard QGIS crash.
            runtime.reset_session()
            return runtime.is_available()
        except Exception as exc:
            print(f"whitebox_workflows is not available: {exc}")
            return False

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
